-- Initial public schema for the HumanAI app.
-- Extracted from a Supabase backup without auth data, chat data, vault data, or secrets.

create extension if not exists pgcrypto with schema extensions;

create or replace function public.trigger_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.chat_folders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz default now(),
  assigned_model text
);

create table public.chat_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  folder_id uuid references public.chat_folders(id) on delete set null
);

create table public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role = any (array['user', 'bot', 'system'])),
  content text not null,
  content_json jsonb,
  created_at timestamptz default now(),
  model_used text,
  input_tokens integer default 0,
  output_tokens integer default 0,
  cost_usd numeric(10,7) default 0
);

create table public.chat_analysis (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.chat_sessions(id) on delete cascade,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  categories jsonb default '[]'::jsonb,
  prompt_quality_score integer,
  prompt_improvement_suggestion text,
  response_match_score integer,
  hallucination_check text,
  hallucination_details text,
  created_at timestamptz default now(),
  rating_metrics jsonb default '{}'::jsonb
);

create table public.llm_categories (
  id integer generated by default as identity primary key,
  slug text not null unique,
  title text not null
);

create table public.prompt_categories (
  id integer generated by default as identity primary key,
  slug text not null unique,
  title text not null
);

create table public.llm_requests (
  id bigint generated by default as identity primary key,
  session_id uuid references public.chat_sessions(id) on delete cascade,
  message_id bigint references public.chat_messages(id) on delete set null,
  user_id uuid references auth.users(id) on delete cascade,
  model text,
  prompt text,
  response text,
  tokens_input integer,
  tokens_output integer,
  duration_ms integer,
  created_at timestamptz default now()
);

create table public.llm_request_categories (
  llm_request_id bigint not null references public.llm_requests(id) on delete cascade,
  category_id integer not null references public.llm_categories(id) on delete cascade,
  primary key (llm_request_id, category_id)
);

create table public.message_prompt_categories (
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  category_id integer not null references public.prompt_categories(id) on delete cascade,
  primary key (message_id, category_id)
);

create view public.view_user_costs
with (security_invoker = true)
as
select
  user_id,
  sum(cost_usd) as total_spend,
  sum(input_tokens) + sum(output_tokens) as total_tokens
from public.chat_messages
group by user_id;

create trigger chat_sessions_updated_at
before update on public.chat_sessions
for each row
execute function public.trigger_set_updated_at();

create index chat_folders_user_id_idx on public.chat_folders(user_id);
create index chat_sessions_user_id_idx on public.chat_sessions(user_id);
create index chat_sessions_folder_id_idx on public.chat_sessions(folder_id);
create index chat_messages_session_id_idx on public.chat_messages(session_id);
create index chat_messages_user_id_created_at_idx on public.chat_messages(user_id, created_at);
create index chat_analysis_user_id_created_at_idx on public.chat_analysis(user_id, created_at);
create index chat_analysis_session_id_idx on public.chat_analysis(session_id);
create index llm_requests_user_id_created_at_idx on public.llm_requests(user_id, created_at);

alter table public.chat_folders enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_analysis enable row level security;
alter table public.llm_categories enable row level security;
alter table public.prompt_categories enable row level security;
alter table public.llm_requests enable row level security;
alter table public.llm_request_categories enable row level security;
alter table public.message_prompt_categories enable row level security;

create policy "Users can manage their own folders"
on public.chat_folders
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users can select own sessions"
on public.chat_sessions
for select
using (auth.uid() = user_id);

create policy "users can insert own sessions"
on public.chat_sessions
for insert
with check (auth.uid() = user_id);

create policy "users can update own sessions"
on public.chat_sessions
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users can delete own sessions"
on public.chat_sessions
for delete
using (auth.uid() = user_id);

create policy "users can select own messages"
on public.chat_messages
for select
using (auth.uid() = user_id);

create policy "users can insert own messages"
on public.chat_messages
for insert
with check (auth.uid() = user_id);

create policy "users can update own messages"
on public.chat_messages
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users can delete own messages"
on public.chat_messages
for delete
using (auth.uid() = user_id);

create policy "Users can see their own analysis"
on public.chat_analysis
for select
using (auth.uid() = user_id);

create policy "Backend/Users can insert analysis"
on public.chat_analysis
for insert
with check (auth.uid() = user_id);

create policy "authenticated users can read llm categories"
on public.llm_categories
for select
to authenticated
using (true);

create policy "authenticated users can read prompt categories"
on public.prompt_categories
for select
to authenticated
using (true);

create policy "users can select own llm_requests"
on public.llm_requests
for select
using (auth.uid() = user_id);

create policy "users can insert own llm_requests"
on public.llm_requests
for insert
with check (auth.uid() = user_id);

create policy "users can delete own llm_requests"
on public.llm_requests
for delete
using (auth.uid() = user_id);

create policy "users can select own llm request categories"
on public.llm_request_categories
for select
using (
  exists (
    select 1
    from public.llm_requests r
    where r.id = llm_request_categories.llm_request_id
      and r.user_id = auth.uid()
  )
);

create policy "users can insert own llm request categories"
on public.llm_request_categories
for insert
with check (
  exists (
    select 1
    from public.llm_requests r
    where r.id = llm_request_categories.llm_request_id
      and r.user_id = auth.uid()
  )
);

create policy "users can select own message categories"
on public.message_prompt_categories
for select
using (
  exists (
    select 1
    from public.chat_messages m
    where m.id = message_prompt_categories.message_id
      and m.user_id = auth.uid()
  )
);

create policy "users can insert own message categories"
on public.message_prompt_categories
for insert
with check (
  exists (
    select 1
    from public.chat_messages m
    where m.id = message_prompt_categories.message_id
      and m.user_id = auth.uid()
  )
);

revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;

grant usage on schema public to authenticated, service_role;
grant select, insert, update, delete on
  public.chat_folders,
  public.chat_sessions,
  public.chat_messages,
  public.chat_analysis,
  public.llm_requests,
  public.llm_request_categories,
  public.message_prompt_categories
to authenticated;
grant select on
  public.llm_categories,
  public.prompt_categories,
  public.view_user_costs
to authenticated;
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to authenticated;
grant all on all sequences in schema public to service_role;

insert into public.llm_categories (id, slug, title) values
  (1, 'assistant', 'Assistant / Generalist'),
  (2, 'summarizer', 'Summarizer'),
  (3, 'codegen', 'Code Generator'),
  (4, 'translator', 'Ubersetzer')
on conflict (id) do update
set slug = excluded.slug,
    title = excluded.title;

insert into public.prompt_categories (id, slug, title) values
  (1, 'product', 'Produkt / Feature'),
  (2, 'bug', 'Bug / Fehlerbericht'),
  (3, 'support', 'Support / Frage'),
  (4, 'sales', 'Verkauf / Pricing'),
  (5, 'code', 'Code / Implementation')
on conflict (id) do update
set slug = excluded.slug,
    title = excluded.title;

select setval(pg_get_serial_sequence('public.llm_categories', 'id'), 4, true);
select setval(pg_get_serial_sequence('public.prompt_categories', 'id'), 5, true);

alter publication supabase_realtime add table
  public.chat_folders,
  public.chat_sessions,
  public.chat_messages,
  public.chat_analysis;
